HE_website/HE_website/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('he_admin.urls'))
]

HE_website/he_admin/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from he_admin import views


app_name='he_admin'
urlpatterns = [
    #categories path

    path('',views.index,name='index'),
    path('addproductscategory',views.add_products_category,name='addcategory'),
    path('showcategories',views.ShowCategory,name='showcategories'),
    path('view/<int:id>/',views.ViewCategory,name='viewcategory'),
    path('edit-category/<int:id>/',views.EditCategory,name='editcategory'),
    path('delete-category/<int:id>/',views.DeleteCategory,name='deletecategory'),
    path('status-category/<int:id>/',views.StatusCategory,name='statuscategory'),

    #Products path
    path('addproducts',views.Add_Products,name='addproducts'),
    path('showproducts',views.ShowProducts,name='showproducts'),
    path('view-product/<int:id>/',views.ViewProduct,name='viewproduct'),
    path('edit-product/<int:id>/',views.EditProduct,name='editproduct'),
    path('delete-product/<int:id>/',views.DeleteProduct,name='deleteproduct'),
    path('status-product/<int:id>/',views.StatusProduct,name='statusproduct'),

    #projects path
    path('addapplications',views.projects,name='project')
    
]
#static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HE_website/he_admin/forms.py
from pyexpat import model
from django import forms
from .models import Products,ProductApplication


class AddProductForm(forms.ModelForm):
    image = forms.ImageField(widget = forms.FileInput(attrs={'class':'form-control'}))
    class Meta:
        model               = Products
        fields              =['category','product_name','Image_alt','image'] 
        labels              ={'product_name':'Product Name '}
        help_text           ={'Image_alt':'Please enter alt tag name for better seo'}
        error_messages      ={'product_name':{'required': 'Please fill the product name'},
                                'image':{'required': 'Please select the image'}} 
        widgets              ={
                                'category':forms.Select(attrs={'class':'form-control'}),
                                'product_name':forms.TextInput(attrs={'class':'form-control'}),
                                
                             }     

class ProductApplicationForm(forms.ModelForm):
    class Meta:
        model = ProductApplication
        fields= ['application_name','image']

HE_website/templates/add_product_category.html
{% extends 'base.html' %}

{% block script %}
{% load static %}
<script type="text/javascript" src="{% static 'ckeditor/ckeditor.js'%}"></script>
{% endblock script %}

{% block title %}Add Product List{% endblock title %}

{% block page-content %}

<div class="content-wrapper" style="min-height: 2171.6px;">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>ADD PRODUCTS CATEGORY</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Add products category</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <section class="content ">
    <div class="container-fluid">

      <div class="col-md-8 offset-2 ">
        <!-- general form elements -->
        <div class="card card-secondary ">
          <div class="card-header">
            <h3 class="card-title">ADD PRODUCTS CATEGORY</h3>
          </div>
          <!-- /.card-header -->
          <!-- form start -->
          <form enctype="multipart/form-data" method='post'>
            {% csrf_token %}
            <div class="card-body">
              <div class="form-group">
                <label for="exampleInputPassword1">PRODUCT CATEGORY</label>
                <input type="text" class="form-control" id="product_category" name='category' required="required"
                  placeholder="PLEASE ENTER PRODUCT CATEGORY TO ADD IN PRODUCT LIST">
              </div>
              {{ error }}


              <div class="form-group">
                <label for="exampleInputPassword1">CATEGORY DESCRIPTION</label>
                <textarea class="ckeditor" id="myEditor" name='description' required="required"
                  placeholder="PLEASE ENTER DESCRIPTION OF THE PRODUCT"></textarea>
              </div>
              <div class="form-group">
                <label for="exampleInputFile">PRODUCT PHOTO</label>
                <input class="form-control" type="file" id="image" name='image' required="required">
              </div>
              {{ image_error }}

             
              <div>       
                <input type="submit" value="Submit" class="btn btn-outline-success ">
             </div>
            </div>
            <!-- /.card-body -->
          </form>
        </div>
				<!-- /.card -->
			</div>
		</div>
	</section>
</div>

<script type="text/javascript">
  //[CDATA[

  CKEDITOR.replace('myEditor',
    {
      fullPage: true,
      uiColor: '#fcfcfc'
    });
  //]]>
</script>

{% endblock page-content %}

HE_website/templates/add_products.html
{% extends 'base.html' %}

{% block title %}Add Products{% endblock title %}

{% block page-content %}

<div class="content-wrapper" style="min-height: 2171.6px;">
	<!-- Content Header (Page header) -->
	<section class="content-header">
		<div class="container-fluid">
			<div class="row mb-2">
				<div class="col-sm-6">
					<h1>ADD PRODUCTS</h1>
				</div>
				<div class="col-sm-6">
					<ol class="breadcrumb float-sm-right">
						<li class="breadcrumb-item"><a href="#">Home</a></li>
						<li class="breadcrumb-item active">Add products</li>
					</ol>
				</div>
			</div>
		</div><!-- /.container-fluid -->
	</section>

	<section class="content ">
		<div class="container-fluid">

			<div class="col-md-8 offset-2 ">
				<!-- general form elements -->
				<div class="card card-primary">
					<div class="card-header">
						<h3 class="card-title">ADD PRODUCTS</h3>
					</div>
					<!-- /.card-header -->
					<!-- form start {% for forms in form  %}{{forms.type}}{% endfor %} -->
					<form enctype="multipart/form-data" method="post" action="" novalidate>
						{% csrf_token %}
						<div class="card-body">

							<div class="form-group ">
								<label for={{form.category.label_id}}> {{form.category.label_tag}} </label>
								<select class="form-control" name={{form.category.name}} id="{{form.category.label_id}}" required="">
									{% for forms in form.category %}
									{{forms}}
									{% endfor %}
								</select>
							</div>
							{% if form.errors.category %}
							<para style="color:red">{{form.errors.category}}</para>
							{% endif %}

							<div class="form-group">
								<label for={{form.product_name.label_id}}>{{form.product_name.label_tag}}</label>
								<input type="text" class="form-control" id="product_name"
									name={{form.product_name.name}} required="required" placeholder="">
							</div>
							{% if form.errors.product_name %}
							<para style="color:red"> {{form.errors.product_name}} </para>
							{% endif %}

							<div class="form-group">
								<label for={{form.Image_alt.label_id}}>{{form.Image_alt.label_tag}}</label>
								<input type="text" class="form-control" id="image_alt" name={{form.Image_alt.name}}
									required="required" placeholder="">
							</div>

							<div class="form-group">
								<label for={{form.image.label_id}}>Product {{form.image.label_tag}}</label>
								<input class="form-control" type="file" name="image" accept="image/*" required="" id="id_image">		
							</div>
							{% if form.errors.image %}
							<para style="color:red"> {{form.errors.image}} </para>
							{% endif %}


							<input type="submit" value="Submit" class="btn btn-outline-success ">

						</div>

					</form>
				</div>
				<!-- /.card -->
			</div>
		</div>
	</section>
</div>
{% endblock page-content %}

HE_website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{% endblock title %}</title>
  {% load static %}
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css'%}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bootstrap 4 -->

  <link rel="stylesheet" href="{%static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{%static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{%static 'plugins/jqvmap/jqvmap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{%static 'css/adminlte.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{%static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{%static 'plugins/daterangepicker/daterangepicker.css' %}">
  <!-- summernote -->
  <link rel="stylesheet" href="{%static 'plugins/summernote/summernote-bs4.min.css' %}">
  {% block script  %}{% endblock script %}
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  <!-- Preloader -->
  <div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__shake" src="dist/img/AdminLTELogo.png" alt="AdminLTELogo" height="60" width="60">
  </div>

  <!-- Navbar -->
  {% include 'navbar.html' %}
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  {% include 'sidebar.html' %}

  <!-- Content Wrapper. Contains page content -->
    <!--Alert -->
    
    {% if messages %}
    {% for message in messages %}
    <div class="alert {{ message.tags }} col-md-2 text-center" style="margin: auto" role="alert" id="msg">
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}

  <!--End Alert-->
 
  {% block page-content%}  {%endblock page-content%}

 
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <strong>Copyright &copy; 2022 <a href="#">HE</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      
    </div>
  </footer>

  <!-- Control Sidebar -->
  
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- JQVMap -->
<script src="{% static 'plugins/jqvmap/jquery.vmap.min.js' %}"></script>
<script src="{% static 'plugins/jqvmap/maps/jquery.vmap.usa.js' %}"></script>
<!-- jQuery Knob Chart -->
<scrip src="{% static 'plugins/jquery-knob/jquery.knob.min.js' %}"></script>
<!-- daterangepicker -->

<script src="{% static 'plugins/daterangepicker/daterangepicker.js' %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<!-- Summernote -->
<script src="{% static 'plugins/summernote/summernote-bs4.min.js' %}"></script>
<!-- overlayScrollbars -->
<script src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'js/adminlte.js' %}"></script>
<!-- AdminLTE for demo purposes <script src="static/js/demo.js"></script> -->

<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'js/pages/dashboard.js' %}"></script>


<!--alert time -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
<script>
  setTimeout(function(){
    if ($('#msg').length > 0) {
      $('#msg').remove();
    }
  }, 2000)
</script> 
<!--alert time end-->

</body>
</html>

HE_website/templates/navbar.html
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
          <i class="fas fa-search"></i>
        </a>
        <div class="navbar-search-block">
          <form class="form-inline">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>

     
         
          <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-user"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fa-solid fa-arrow-right-from-bracket"></i>Log Out
          </a>
         </div>
      </li>
     
    </ul>
  </nav>

  <!-- /.navbar -->

 

HE_website/templates/projects.html
{% extends 'base.html' %}

{% block title %}Add Products{% endblock title %}

{% block page-content %}

<div class="content-wrapper" style="min-height: 2171.6px;">
	<!-- Content Header (Page header) -->
	<section class="content-header">
		<div class="container-fluid">
			<div class="row mb-2">
				<div class="col-sm-6">
					<h1>PRODUCTS APPLICATIONS</h1>
				</div>
				<div class="col-sm-6">
					<ol class="breadcrumb float-sm-right">
						<li class="breadcrumb-item"><a href="#">Home</a></li>
						<li class="breadcrumb-item active">Product Applications</li>
					</ol>
				</div>
			</div>
		</div><!-- /.container-fluid -->
	</section>

	<section class="content ">
		<div class="container-fluid">

			<div class="col-md-8 offset-2 ">
				<!-- general form elements -->
				<div class="card card-primary">
					<div class="card-header">
						<h3 class="card-title">ADD PRODUCTS</h3>
					</div>
					<!-- /.card-header -->
					<!-- form start {% for forms in form  %}{{forms.type}}{% endfor %} -->
					<form enctype="multipart/form-data" method="post" action="" novalidate>
						{% csrf_token %}
						<div class="card-body">

							<div class="form-group ">
								<label for={{form.application_name.label_id}}> {{form.application_name.label_tag}} </label>
								<input type="text" class="form-control" id="application_name"
									name={{form.application_name.name}} required="required" placeholder="">
							</div>
							{% if form.errors.application_name %}
							<para style="color:red">{{form.errors.application_name}}</para>
							{% endif %}

							<div class="form-group">
								<label for={{form.image.label_id}}>{{form.image.label_tag}}</label>
								<input class="form-control" type="file" name="image" accept="image/*" required="" id="id_image">		
							</div>
							{% if form.errors.image %}
							<para style="color:red"> {{form.errors.image}} </para>
							{% endif %}


							<input type="submit" value="Submit" class="btn btn-outline-success ">

						</div>

					</form>
				</div>
				<!-- /.card -->
			</div>
		</div>
	</section>
</div>
{% endblock page-content %}

HE_website/templates/show-products.html
{% extends 'base.html' %}
 {% block title %}show products{% endblock title %}

 {% block page-content %}
 
 <div class="content-wrapper" style="min-height: 2171.6px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>CATEGORIES</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">categories</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
  
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
  
              <!-- /.card-header -->
              <div class="card-body">
                <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
                  <div class="row">
                    <div class="col-sm-12 col-md-6">
  
                    </div>
                    <div class="col-sm-12 col-md-6">
  
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-sm-12">
                      <table id="table_id" class="table table-bordered table-hover dataTable dtr-inline"
                        aria-describedby="example2_info">
                        <thead>
                          <tr>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                              aria-label="Browser: activate to sort column ascending">S.No</th>
                            <th class="sorting sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                              aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending">Category Name
                            </th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                              aria-label="Platform(s): activate to sort column ascending">Product Name(s)</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                              aria-label="Engine version: activate to sort column ascending">Image</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                              aria-label="CSS grade: activate to sort column ascending">Operation</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                              aria-label="CSS grade: activate to sort column ascending">Status</th>
                          </tr>
                        </thead>
                        <tbody>
                          {%for product in products%}
                          <tr class="even">
                            <td class="dtr-control sorting_1" tabindex="0">{{forloop.counter}}</td>
                            <td>{{product.category}}</td>
                            <td>
                              {{product.product_name }}
                            </td>
                            <td><img src="static{{product.image.url}}" height="60px" width="80px"></td>
                            <td>
                              <a href="{% url 'he_admin:viewproduct' product.id %}" class="btn btn-outline-info" title="View" ><i class="far fa-eye"></i></a>
                             
                              <a href="{% url 'he_admin:editproduct' product.id %}" class="btn btn-outline-success" title="Update"><i class="far fa-edit"></i></a>
                              <a href="{% url 'he_admin:deleteproduct' product.id %}" class="btn btn-outline-danger" title="Permanent Delete"><i
                                  class="fas fa-times"></i></a>
                            </td>
                            <td>
                              {% if product.status %}
                              <a href="{% url 'he_admin:statusproduct' product.id %}" class="btn btn-outline-success" title="Click For Disabled"><i
                                  class="fas fa-toggle-on" value={{product.status}}></i></a>
                                 {% else %}
                              <a href="{% url 'he_admin:statusproduct' product.id %}" class="btn btn-outline-danger" title="Click For Enabled"><i
                                  class="fas fa-toggle-off" value={{product.status}}></i></a>
                                  {% endif %}
                            </td>
                          </tr>
                          {%empty%}
                          <li>Sorry, no category is available</li>
                          {% endfor %}
                        </tbody>
                      </table>
                    </div>
                  </div>
                  
                  <!-- /.row -->
                </div>
              </div>
            </div>
          </div>  
        </div>
      </div>  <!-- /.container-fluid -->
    </section>
  </div>
  
  <!--datatable script-->
  <script>
  $(document).ready( function () {
    $('#table_id').DataTable();
  } );
  </script>
  <!--end datatable script-->
  
 
 {% endblock page-content %}

HE_website/templates/show_category.html
{% extends 'base.html' %}

{% block title %}categories{% endblock title %}
{% block script %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css">
  
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.js"></script>
{% endblock script %}
{% block page-content %}
<div class="content-wrapper" style="min-height: 2171.6px;">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>CATEGORIES</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">categories</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">
          <div class="card">

            <!-- /.card-header -->
            <div class="card-body">
              <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <div class="row">
                  <div class="col-sm-12 col-md-6">

                  </div>
                  <div class="col-sm-12 col-md-6">

                  </div>
                </div>
                <div class="row">
                  <div class="col-sm-12">
                    <table id="table_id" class="table table-bordered table-hover dataTable dtr-inline"
                      aria-describedby="example2_info">
                      <thead>
                        <tr>
                          <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                            aria-label="Browser: activate to sort column ascending">S.No</th>
                          <th class="sorting sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                            aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending">Name
                          </th>
                          <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                            aria-label="Platform(s): activate to sort column ascending">Description(s)</th>
                          <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                            aria-label="Engine version: activate to sort column ascending">Image</th>
                          <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                            aria-label="CSS grade: activate to sort column ascending">Operation</th>
                          <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                            aria-label="CSS grade: activate to sort column ascending">Status</th>
                        </tr>
                      </thead>
                      <tbody>
                        {%for category in categories%}
                        <tr class="even">
                          <td class="dtr-control sorting_1" tabindex="0">{{forloop.counter}}</td>
                          <td>{{category.category}}</td>
                          <td>
                            {{category.description | safe}}
                          </td>
                          <td><img src="static{{category.category_image.url}}" height="60px" width="80px"></td>
                          <td>
                            <a href="{% url 'he_admin:viewcategory' category.id %}" class="btn btn-outline-info" title="View" ><i class="far fa-eye"></i></a>
                           
                            <a href="{% url 'he_admin:editcategory' category.id %}" class="btn btn-outline-success" title="Update"><i class="far fa-edit"></i></a>
                            <a href="{% url 'he_admin:deletecategory' category.id %}" class="btn btn-outline-danger" title="Permanent Delete"><i
                                class="fas fa-times"></i></a>
                          </td>
                          <td>
                            {% if category.status %}
                            <a href="{% url 'he_admin:statuscategory' category.id %}" class="btn btn-outline-success" title="Click For Disabled"><i
                                class="fas fa-toggle-on" value={{category.status}}></i></a>
                               {% else %}
                            <a href="{% url 'he_admin:statuscategory' category.id %}" class="btn btn-outline-danger" title="Click For Enabled"><i
                                class="fas fa-toggle-off" value={{category.status}}></i></a>
                                {% endif %}
                          </td>
                        </tr>
                        {%empty%}
                        <li>Sorry, no category is available</li>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
                
                <!-- /.row -->
              </div>
            </div>
          </div>
        </div>  
      </div>
    </div>  <!-- /.container-fluid -->
  </section>
</div>

<!--datatable script-->
<script>
$(document).ready( function () {
  $('#table_id').DataTable();
} );
</script>
<!--end datatable script-->

{% endblock page-content %}

HE_website/templates/viewcategory.html
{% extends 'base.html' %}

{% block page-content %}

<div class="content-wrapper" style="min-height: 2171.6px;">
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>CATEGORIES</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item">Home</li>
            <li class="breadcrumb-item">category</li>
            <li class="breadcrumb-item active">view</li>
          </ol>
        </div>
      </div>
    </div>
    <!-- /.container-fluid -->
  </section>
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-10 offset-1">
          <div class="card">
            <div class="card card-info">
              <div class="card-header">
                <h3 class="card-title">View Category</h3>
              </div>
            </div>
              <div class="card-body">

                  <div class="text-center">
                    <img src="/static{{category.category_image.url}}" class="rounded img-fluid" style="width: 600px; height:400px;" />
                  </div>
                  <div class="text-center">
                    <label>{{category.category}}</label>
                  </div>
                    <div class="col-sm-8">
                      <p>{{category.description | safe}}</p>
                    </div>
                    
              </div>
              <div class="card-footer">
                <a href="{% url 'he_admin:showcategories' %}"  class="btn btn-info">Back</a> 
              </div>
         
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

{% endblock page-content %}

HE_website/templates/viewproduct.html
{% extends 'base.html' %}

{% block page-content %}

<div class="content-wrapper" style="min-height: 2171.6px;">
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>CATEGORIES</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item">Home</li>
            <li class="breadcrumb-item">category</li>
            <li class="breadcrumb-item active">view</li>
          </ol>
        </div>
      </div>
    </div>
    <!-- /.container-fluid -->
  </section>
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-10 offset-1">
          <div class="card">
            <div class="card card-info">
              <div class="card-header">
                <h3 class="card-title">View Product</h3>
              </div>
            </div>
              <div class="card-body">

                  <div class="text-center">
                    <img src="/static{{product.image.url}}" class="rounded img-fluid" style="width: 600px; height:400px;" />
                  </div>
                  <div class="text-center">
                    <label>CATEGORY : {{product.category}}</label>
                  </div>
                  <div class="text-center">
                    <label>PRODUCT : {{product.product_name}}</label>
                  </div>
                    
              </div>
              <div class="card-footer">
                <a href="{% url 'he_admin:showproducts' %}"  class="btn btn-info">Back</a> 
              </div>
         
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

{% endblock page-content %}